language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0

branches:
  only:
    - master

before_script:
- composer install -n --dev --prefer-source

script: composer test

notifications:
  email:
    - kayzorelabs@gmail.com
